In [1]:
# basic
import numpy as np
import pandas as pd

# get data
# ! conda install pandas-datareader s
import pandas_datareader as pdr

# visual
# ! pip install mpl-finance
import matplotlib.pyplot as plt
import mpl_finance as mpf
%matplotlib inline
import seaborn as sns

#time
import datetime as datetime

# https://github.com/mrjbq7/ta-lib
# ! pip install ta-lib 
import talib

In [3]:
start_date = datetime.datetime(2018,1,1)     #開始日期
end_date= datetime.datetime(2018,12,31)      #結束日期

In [4]:
df_2327 = pdr.DataReader('2327.TW', 'yahoo', start=start_date ,end=end_date)   # 台灣國巨
df_2327.head()

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2018-01-02,295.463989,285.447998,294.628998,295.463989,2750944.0,291.178375
2018-01-03,324.675995,303.809998,308.401001,324.675995,5169187.0,319.966675
2018-01-04,350.549988,328.848999,334.691986,332.605011,12046913.0,327.780670
2018-01-05,346.377014,322.589996,330.101013,337.196014,6620085.0,332.305084
2018-01-08,337.196014,328.432007,337.196014,333.856995,3889273.0,329.014496

In [5]:
df_2327['Date']=df_2327.index             # index 複製到另一欄
df_2327 = df_2327.reset_index(drop=True)  # index變成 0~N
df_2327.head()

,High,Low,Open,Close,Volume,Adj Close,Date
0,295.463989,285.447998,294.628998,295.463989,2750944.0,291.178375,2018-01-02
1,324.675995,303.809998,308.401001,324.675995,5169187.0,319.966675,2018-01-03
2,350.549988,328.848999,334.691986,332.605011,12046913.0,327.780670,2018-01-04
3,346.377014,322.589996,330.101013,337.196014,6620085.0,332.305084,2018-01-05
4,337.196014,328.432007,337.196014,333.856995,3889273.0,329.014496,2018-01-08

In [6]:
##增欄位:fluctuation幅度 tag漲跌平
df_2327['fluctuation']=0
df_2327['tag']='--'
df_2327.head()

,High,Low,Open,Close,Volume,Adj Close,Date,fluctuation,tag
0,295.463989,285.447998,294.628998,295.463989,2750944.0,291.178375,2018-01-02,0,--
1,324.675995,303.809998,308.401001,324.675995,5169187.0,319.966675,2018-01-03,0,--
2,350.549988,328.848999,334.691986,332.605011,12046913.0,327.780670,2018-01-04,0,--
3,346.377014,322.589996,330.101013,337.196014,6620085.0,332.305084,2018-01-05,0,--
4,337.196014,328.432007,337.196014,333.856995,3889273.0,329.014496,2018-01-08,0,--

In [8]:
###計算漲跌
for index, row in df_2327.iterrows():
    try:
        margin =(float(df_2327.loc[index,'High']) - float(df_2327.loc[index-1,'Close']) )/ float(df_2327.loc[index-1,'Close'])
        df_2327.loc[index,'fluctuation']=margin
        if margin >0.03:
            df_2327.loc[index,'tag']='up'
        elif margin<-0.03:
            df_2327.loc[index,'tag']='down'
    except:
        continue

In [9]:
up_fliter=(df_2327['tag']=='up')
up_2327=df_2327[up_fliter]
up_2327

,High,Low,Open,Close,Volume,Adj Close,Date,fluctuation,tag
1,324.675995,303.809998,308.401001,324.675995,5169187.0,319.966675,2018-01-03,0.098868,up
2,350.549988,328.848999,334.691986,332.605011,12046913.0,327.780670,2018-01-04,0.079692,up
3,346.377014,322.589996,330.101013,337.196014,6620085.0,332.305084,2018-01-05,0.041406,up
7,338.029999,320.502991,330.101013,322.589996,9734149.0,317.910950,2018-01-11,0.067192,up
12,307.148987,295.881012,298.802002,302.140991,8464482.0,297.758545,2018-01-18,0.036622,up
13,324.675995,304.644989,307.148987,324.675995,7269191.0,319.966675,2018-01-19,0.074584,up
14,351.802002,318.834015,320.502991,346.377014,12769254.0,341.352936,2018-01-22,0.083548,up
21,327.179993,304.644989,305.479004,323.006989,5759438.0,318.321869,2018-01-31,0.050938,up
23,343.872986,331.770996,335.527008,333.856995,9784255.0,329.014496,2018-02-02,0.067358,up
26,315.494995,298.385010,308.817993,298.385010,6880590.0,294.057037,2018-02-07,0.067795,up
29,287.535004,260.408997,283.778992,260.408997,10239903.0,256.631836,2018-02-12,0.039218,up
30,275.432007,267.085999,273.763000,272.093994,8856999.0,268.147369,2018-02-21,0.057690,up
32,293.377014,271.259003,292.959991,271.259003,13181911.0,267.324493,2018-02-23,0.074925,up
35,288.786011,273.763000,276.266998,288.786011,9360799.0,284.597260,2018-03-01,0.046895,up
36,315.494995,286.282990,287.117004,305.062012,14738983.0,300.637177,2018-03-02,0.092487,up
37,319.251007,309.653015,317.164001,314.660004,11419947.0,310.095978,2018-03-05,0.046512,up
39,333.856995,315.078003,315.494995,328.432007,9225151.0,323.668213,2018-03-07,0.043023,up
41,348.045990,328.848999,333.856995,338.447998,13412711.0,333.538910,2018-03-09,0.041197,up
42,349.714996,341.368988,343.455994,342.204010,6100082.0,337.240448,2018-03-12,0.033290,up
47,368.078003,351.385010,353.053986,368.078003,7548212.0,362.739166,2018-03-19,0.037649,up
48,389.778015,362.234985,364.739014,389.778015,12849713.0,384.124420,2018-03-20,0.058955,up
49,407.722992,391.447998,391.864990,407.306000,11427449.0,401.398163,2018-03-21,0.046039,up
50,428.171997,413.983002,417.321991,423.164001,13073409.0,417.026154,2018-03-22,0.051229,up
53,423.998993,403.967010,408.140015,419.825012,8438982.0,413.735596,2018-03-27,0.069476,up
55,438.187988,418.990997,423.998993,434.014008,5367965.0,427.718781,2018-03-29,0.060608,up
56,473.243011,434.014008,444.029999,435.683990,7511061.0,429.364532,2018-03-30,0.090386,up
57,449.037994,417.321991,444.029999,419.825012,6225240.0,413.735596,2018-04-02,0.030651,up
59,444.029999,421.494995,428.171997,444.029999,6360655.0,437.589478,2018-04-09,0.041095,up
60,466.565002,440.691986,451.541992,454.880005,10895314.0,448.282135,2018-04-10,0.050751,up
61,473.243011,451.541992,465.730988,454.045990,6739319.0,447.460205,2018-04-11,0.040369,up
...,...,...,...,...,...,...,...,...,...
157,703.000000,658.000000,658.000000,695.000000,18787089.0,695.000000,2018-08-27,0.093313,up
159,706.000000,681.000000,688.000000,705.000000,14784910.0,705.000000,2018-08-29,0.045926,up
168,567.000000,534.000000,546.000000,546.000000,17750844.0,546.000000,2018-09-11,0.065789,up
170,548.000000,507.000000,541.000000,508.000000,14845213.0,508.000000,2018-09-13,0.037879,up
171,546.000000,500.000000,523.000000,534.000000,26331854.0,534.000000,2018-09-14,0.074803,up
174,522.000000,475.500000,511.000000,479.000000,24448387.0,479.000000,2018-09-19,0.041916,up
175,497.500000,461.000000,480.000000,490.000000,30158497.0,490.000000,2018-09-20,0.038622,up
176,514.000000,494.500000,506.000000,514.000000,20913214.0,514.000000,2018-09-21,0.048980,up
187,428.500000,404.500000,410.000000,423.500000,25457620.0,423.500000,2018-10-09,0.060644,up
189,424.500000,390.000000,391.000000,415.000000,25896737.0,415.000000,2018-10-12,0.094072,up
190,428.500000,409.000000,415.000000,410.000000,21216901.0,410.000000,2018-10-15,0.032530,up
191,427.000000,410.500000,412.000000,419.000000,18948993.0,419.000000,2018-10-16,0.041463,up
192,448.500000,417.500000,445.000000,418.000000,24411631.0,418.000000,2018-10-17,0.070406,up
199,332.000000,313.500000,332.000000,324.000000,32901186.0,324.000000,2018-10-26,0.052298,up
202,325.500000,305.000000,305.000000,315.500000,33262695.0,315.500000,2018-10-31,0.092282,up
203,347.000000,319.000000,320.000000,347.000000,33748728.0,347.000000,2018-11-01,0.099842,up
204,381.000000,336.000000,365.500000,345.500000,47888835.0,345.500000,2018-11-02,0.097983,up
207,335.500000,301.000000,309.000000,331.000000,34806190.0,331.000000,2018-11-07,0.089286,up
208,350.000000,323.000000,348.000000,324.000000,28611410.0,324.000000,2018-11-08,0.057402,up
214,325.000000,310.000000,317.000000,310.000000,21075109.0,310.000000,2018-11-16,0.041667,up
217,340.000000,318.500000,318.500000,340.000000,26079710.0,340.000000,2018-11-21,0.059190,up
218,351.500000,329.500000,345.000000,332.000000,27264523.0,332.000000,2018-11-22,0.033824,up
221,344.000000,326.500000,327.500000,340.000000,20575693.0,340.000000,2018-11-27,0.051988,up
222,371.500000,341.000000,347.000000,357.500000,31648912.0,357.500000,2018-11-28,0.092647,up
223,377.000000,357.500000,373.000000,359.500000,31718932.0,359.500000,2018-11-29,0.054545,up
225,407.000000,387.500000,387.500000,407.000000,20895584.0,407.000000,2018-12-03,0.100000,up
231,334.500000,322.500000,325.500000,332.000000,17962644.0,332.000000,2018-12-11,0.034003,up
232,344.000000,338.000000,340.500000,338.500000,14055814.0,338.500000,2018-12-12,0.036145,up
239,328.000000,307.000000,312.000000,328.000000,19012517.0,328.000000,2018-12-21,0.044586,up
243,331.000000,319.000000,328.000000,321.000000,19997693.0,321.000000,2018-12-27,0.054140,up

In [10]:
down_fliter=(df_2327['tag']=='down')
down_2327=df_2327[down_fliter]
down_2327

,High,Low,Open,Close,Volume,Adj Close,Date,fluctuation,tag
28,281.274994,264.582001,270.424011,276.68399,7312186.0,272.670776,2018-02-09,-0.031609,down
124,1010.000000,959.000000,980.000000,965.00000,12645857.0,965.000000,2018-07-11,-0.033493,down
188,400.500000,384.500000,384.500000,388.00000,27473826.0,388.000000,2018-10-11,-0.054309,down
194,408.000000,389.000000,405.000000,394.00000,26319320.0,394.000000,2018-10-19,-0.032028,down
198,330.500000,315.500000,328.000000,315.50000,24997923.0,315.500000,2018-10-25,-0.053009,down
210,313.500000,304.000000,307.000000,310.00000,21406188.0,310.000000,2018-11-12,-0.047112,down
230,345.000000,322.000000,344.500000,323.50000,23304104.0,323.500000,2018-12-10,-0.032258,down

In [38]:
downDate=down_2327["Date"].astype(str)
downDate

28     2018-02-09
124    2018-07-11
188    2018-10-11
194    2018-10-19
198    2018-10-25
210    2018-11-12
230    2018-12-10
Name: Date, dtype: object

In [20]:
df_forum = pd.read_csv("bda2019_dataset/forum2.csv",encoding="utf-8")

In [22]:
df_forum[['post_time','title','content']]

,post_time,title,content
0,2016/1/1 2:01:00,自刪,不小心發錯版主請幫忙刪除文章謝謝
1,2016/1/1 10:41:00,傳超微已打算將訂單下給格羅方德,台積電爭奪超微下一代繪圖處理器失利，因為傳超微已打算將訂單下給格羅方德（GlobalFoun...
2,2016/1/1 10:45:00,蘋果將另尋成長動能發動購併 ??,有分析師認為 蘋果將另尋成長動能，或許會動用深到不行的口袋，發動購併，可能目標包括 Adob...
3,2016/1/1 11:19:00,[詢問] 停徵證所稅,新聞相關報導:<BR>[立法院院會去年11月三讀修正通過所得稅法部分條文，刪除有關證所稅相關...
4,2016/1/1 12:29:00,網路出金,請問一下，網路出金是什麼？謝謝各位喔。
5,2016/1/1 12:49:00,這情況 是銀行多給利息嗎！,大家，新年快樂<BR>想請問大家，在網銀設定定存半年，在今天105/01/01到期，<BR>...
6,2016/1/1 16:15:00,元大S&P500或開美國卷商買S&P500哪個好?,這陣子知道元大也有S&P500<BR>且自己上網查閱了另一種<BR>就是線上開美國證卷戶的方...
7,2016/1/1 16:28:00,請問各位學技術分析的大大們 那些指標好用呢？,請問各位大大 小弟如果想作短線 有那些技術指標比較實用比較準的呢？可否推薦一下呢？
8,2016/1/1 16:59:00,貧富差距不斷增加，你該如何自保？,台灣曾經有過均富的黃金時代!!<BR>那個時候是台灣經濟起飛的時候<BR>還記得台灣的平均所...
9,2016/1/1 20:00:00,鴻海股價最近低迷,鴻海最近股價低迷 是發生什麼狀況嗎?<BR>是否可在進場?求解
10,2016/1/1 22:21:00,賠，賠，賠 -- 我過的好難受啊！,2015 真難受。<BR>賠了 5%。<BR>有人比我慘嗎？
11,2016/1/1 22:26:00,"南非幣要破2了,要停損嗎?還是繼續加碼.","南非幣從4.2開始買,都存定存,3.4時又大買 一批,<BR>總共約65萬南非幣,我也不知道..."
12,2016/1/1 22:43:00,大成感覺不錯 有人上車了嗎???,理由<BR>1 成交量創新高<BR>2 股價創8/7以來新高<BR>3 近期法人持續買超<B...
13,2016/1/2 1:55:00,2016看好的概念股,過去的已經過去，總該有些成長，把跌倒當經驗，展望未來有甚麼是未來十年的希望?<BR>這些概念...
14,2016/1/2 9:31:00,想請問使用現金加油的加油卡(非信用卡),因為各大加油站網站上都沒寫~~~<BR>不知道有大大有推薦哪幾家有可申辦使用現金加油的優惠加...
15,2016/1/2 10:03:00,請問金管會接管朝陽人壽.儲蓄險保戶會有哪些影響?,金管會接管朝陽人壽 <BR>請問短年期儲蓄險保戶會有哪些影響?<BR>===========...
16,2016/1/2 11:04:00,信用卡建議~~,小弟每月固定會刷高鐵回數票(8000)<BR>另外手機跟電視帳單有中華電信、亞太電信、TBC...
17,2016/1/2 12:23:00,人民幣又見急跌 2015全年跌幅註定寫新紀錄,人民幣兌美元周四 (31日) 持續下跌，在歷經近 5 個月大幅波動之後，全年跌幅預計達 4....
18,2016/1/2 16:14:00,【請教】選股軟體 (泰穎製作所),"請問各位高手<BR>大家在選股時,會另外再使用特別的軟體來選股嗎?<BR>這套軟體有沒有人使..."
19,2016/1/2 17:06:00,請問機車險，50cc的要怎樣選擇？,只要保強制和第三責任嗎？<BR>保那家較好，<BR>有推薦的保險公司？<BR>怎樣搭配好<B...
20,2016/1/2 17:11:00,加薪能救景氣 ?,加薪能救景氣 ?<BR>那為什麼現在可以加不趕快加呢 ? 為什麼現在不把基本工資調到4萬 ?
21,2016/1/2 19:04:00,９月那波急拉上去，看到一線生機！成功獲利,相信大家，對於８╱２５還記憶猶新吧！！<BR>當大家都悲觀的時候，從７２００點，一口氣漲到８...
22,2016/1/2 20:58:00,該怎麼創造被動收入 達每個月有三萬,小弟我現在存款有82萬多<BR>每個月基本薪資有6萬5 偶爾會有客製化家具兼差 (但這個兼差...
23,2016/1/2 23:39:00,100 萬現金支出怎麼得到優惠?,小弟因為要買車，故將有大筆現金支出，約100萬.<BR>想問看看有沒有其他方式讓花出去的錢收...
24,2016/1/3 0:30:00,2016/1/1 至 2/29,接替2015年持股<BR>觀察2015年的勝敗數<BR>10天的周期<BR>勝率最高<BR>...
25,2016/1/3 13:13:00,國泰金尾盤,在這天 國泰金尾盤買單大灌快1萬張<BR> 此時的我只想等明天開盤空國泰金... <BR>大...
26,2016/1/3 15:14:00,請問現行的新股抽籤制度 ???,http://udn.com/news/story/7239/1218822-IPO%E7%...
27,2016/1/3 15:37:00,怒火特攻隊真是大爛片,"最後一場戰鬥戲碼真的是沒服過兵役的人編導的.<BR>美軍既已反攻至德國領土, 表示勝利在望,..."
28,2016/1/3 15:44:00,請教機車險幾個問題,請問下<BR>1.<BR>若機車是成年人的<BR>若將來有保第三和強制險<BR>無照未成年小...
29,2016/1/3 16:10:00,理財賺錢有時是天命,同學A買了100張股票，股價大漲加上股利豐富，幾年後身價破數千萬<BR>同學B買了前公司股票...
...,...,...,...
25922,2018/12/30 7:09:00,ASUS華碩 歷史股價觀察買低賣高的高手券商,ASUS華碩是一間台灣之光的上市公司，一般來說國人多少都有用過他的電子產品，像是桌機、筆電、...
25923,2018/12/30 9:16:00,債券,因市場諸多不可測因素<BR>為避免網友真實仿效而導致虧損<BR>因此版主選擇將此版下架<BR...
25924,2018/12/30 10:01:00,基本工資又漲了，你拿到了嗎？,1/1開始<BR>基本工資又漲了<BR>小姐早早就問我<BR>她的工資怎麼算<BR>工作了一...
25925,2018/12/30 10:11:00,我的基金投資配置,年底前因為急需用到一筆錢，只能先把手上的基金先贖回，20多萬的本金，小虧幾千元。<BR>原先...
25926,2018/12/30 10:50:00,10年來最慘!信用卡好康大縮水,搶在跨入2019年前夕，信用卡新年度權益全數出爐，不只回饋率腰斬，能想到的各項權益，包括市區...
25927,2018/12/30 11:49:00,美金高利定存?,想請問那家最高?<BR>年利率 單純定存不做商品<BR>不要階梯式跟短期那種<BR>謝謝
25928,2018/12/30 13:15:00,利安資金越南基金 VS 越南ETF(VNM) @五線譜投資術,最近看到五線譜投資術作者在FB上有簡短提到越南市場的現況與前景，<BR>專業又忙碌如他還是花...
25929,2018/12/30 16:34:00,請問股票股利約幾月公佈,請問股票股票股利約在幾月會公佈？
25930,2018/12/30 18:26:00,請問大家看年報季報是用什麼平台看的?,"因為現在很少公司會發紙本了,都用PDF檔,如果在電腦上看實在很傷眼,而且一家要看十年以上,就..."
25931,2018/12/30 21:35:00,台灣現有ETF(107/12/28)。,1.黃底 ─ 50億以上，0.4%以下。<BR>2.藍底 ─ 5億以下，1%以上。<BR>3...
25932,2018/12/30 22:55:00,2019元旦行情，台股恐上看11000,1/2漲500點<BR>1/3漲400點<BR>1/4漲300點<BR>不要說不可能，<BR...
25933,2018/12/31 1:16:00,買iShares US Preferred Stock ETF (PFF)做為長期投資，比起...,原本想說買iShares US Preferred Stock ETF (PFF)會比買個別...
25934,2018/12/31 2:32:00,有個貸款問題想請教,小弟有一筆國泰世華信貸分84期年利率9%多(貸這筆時因當時評分條件較差，近一年有預借現金及信...
25935,2018/12/31 7:22:00,2019可取代line pay的信用卡？,2%且無回饋金額限制<BR>和linepay 定位一樣的卡有嗎？<BR>用慣linepay ...
25936,2018/12/31 9:43:00,0050是不是請了很多寫手，坊間一大票文章都是推崇,首先不可否認0050在這幾年確實是賺了股利贏了價差，許多文章也極力推崇，元大就賺管理費經理費...
25937,2018/12/31 11:17:00,信用卡分期 & 小額信貸,如果有一筆約30萬的需求，請問是刷卡後申請信用卡分期(最多30期)好? 還是申請小額信貸(最...
25938,2018/12/31 11:49:00,防洗錢需要這麼擾民 ? 資料更新變擾民運動,防洗錢新制 資料更新變擾民運動<BR><BR> <BR>2018-12-31 01:53聯合...
25939,2018/12/31 13:21:00,股市的the less is more,在股票的世界裡，我是一位信奉「the less is more」的投資人，換句話說，我相信做...
25940,2018/12/31 14:54:00,想掛機賺錢看這邊 掛機只要掛到1BTC就等於賺3949.3美金,想掛機賺錢看這邊 掛機只要掛到1BTC就等於賺3949.3美金<BR>想挑戰看看嗎? 掛機賺...
25941,2018/12/31 15:06:00,電腦放著在那邊也是閒著�� 不如拿來簡單又免費挖比特幣吧~~,超低提款門檻只要(0.0004000 BTC)就可以提領！<BR>以運算速度26左右大概4?...
25942,2018/12/31 16:21:00,2430燦坤當定存股可否,配股配息都5%以上<BR>股價來到相對低點<BR>有人有關注到嗎
25943,2018/12/31 16:22:00,不小心公開 證卷帳號11碼 怎辦,不小心公開 證卷帳號11碼 怎辦？<BR>會被盜用嗎？
25944,2018/12/31 17:49:00,防洗錢新制…銀行資料更新 變擾民運動,新聞資料<BR>請問<BR>我不知道我是否有被通知，<BR>我錢那麼少，<BR>到底要不要K...
25945,2018/12/31 18:21:00,2019台新gogo卡超商問題,台新gogo說<BR>2019年回饋之3.5%<BR>排除一切任何一切型式的超商消費<BR>...
25946,2018/12/31 18:37:00,改變消費習慣，你也可以翻轉人生,行動支付正在改變我們的消費模式，食衣住行現在越來越方便，只要手機「嗶」一下就通通搞定，而支付...
25947,2018/12/31 18:59:00,每年保費約250萬，辦哪一張信用卡繳費最好,請問這裡有信用卡達人可以指教一下嗎?每年的保費.都是儲蓄險多，大約250-300萬之間，<B...
25948,2018/12/31 20:09:00,一則美債新聞分享,"這是今天的新聞,作為一位投資者,看完後也分享給大家,但我沒投資美債,對新聞內容也沒有評論~<..."
25949,2018/12/31 20:16:00,股市贏家魔法書-股海真經 全文免費線上閱覽,股市贏家魔法書-股海真經<BR>全文免費線上閱覽<BR>http://stock.nett.tw
25950,2018/12/31 20:27:00,2018年中國夢(雞金暴跌),2018年最后一?交易日落下帷幕，?受?注的公募基金年度排名大??埃落定。<BR>在288只...
25951,2018/12/31 21:20:00,股票為什麼會漲？股票為什麼會跌？,股票為什麼會漲？股票為什麼會跌？<BR>股票為什麼會漲？股票為什麼會跌？ - Google ...

In [39]:
###開始做兩種資料表中的時間比對
forumDate=df_forum['post_time'].astype(str)
forumDate

0           2016/1/1 2:01:00
1          2016/1/1 10:41:00
2          2016/1/1 10:45:00
3          2016/1/1 11:19:00
4          2016/1/1 12:29:00
5          2016/1/1 12:49:00
6          2016/1/1 16:15:00
7          2016/1/1 16:28:00
8          2016/1/1 16:59:00
9          2016/1/1 20:00:00
10         2016/1/1 22:21:00
11         2016/1/1 22:26:00
12         2016/1/1 22:43:00
13          2016/1/2 1:55:00
14          2016/1/2 9:31:00
15         2016/1/2 10:03:00
16         2016/1/2 11:04:00
17         2016/1/2 12:23:00
18         2016/1/2 16:14:00
19         2016/1/2 17:06:00
20         2016/1/2 17:11:00
21         2016/1/2 19:04:00
22         2016/1/2 20:58:00
23         2016/1/2 23:39:00
24          2016/1/3 0:30:00
25         2016/1/3 13:13:00
26         2016/1/3 15:14:00
27         2016/1/3 15:37:00
28         2016/1/3 15:44:00
29         2016/1/3 16:10:00
                ...
25922     2018/12/30 7:09:00
25923     2018/12/30 9:16:00
25924    2018/12/30 10:01:00
25925    2018/12/30 10:11:00
25926    2018/12/30 10:50:00
25927    2018/12/30 11:49:00
25928    2018/12/30 13:15:00
25929    2018/12/30 16:34:00
25930    2018/12/30 18:26:00
25931    2018/12/30 21:35:00
25932    2018/12/30 22:55:00
25933     2018/12/31 1:16:00
25934     2018/12/31 2:32:00
25935     2018/12/31 7:22:00
25936     2018/12/31 9:43:00
25937    2018/12/31 11:17:00
25938    2018/12/31 11:49:00
25939    2018/12/31 13:21:00
25940    2018/12/31 14:54:00
25941    2018/12/31 15:06:00
25942    2018/12/31 16:21:00
25943    2018/12/31 16:22:00
25944    2018/12/31 17:49:00
25945    2018/12/31 18:21:00
25946    2018/12/31 18:37:00
25947    2018/12/31 18:59:00
25948    2018/12/31 20:09:00
25949    2018/12/31 20:16:00
25950    2018/12/31 20:27:00
25951    2018/12/31 21:20:00
Name: post_time, Length: 25952, dtype: object