In [1]:
# basic
import numpy as np
import pandas as pd

# get data
# ! conda install pandas-datareader s
import pandas_datareader as pdr

# visual
# ! pip install mpl-finance
import matplotlib.pyplot as plt
import mpl_finance as mpf
%matplotlib inline
import seaborn as sns

#time
import datetime as datetime

# https://github.com/mrjbq7/ta-lib
# ! pip install ta-lib 
import talib

In [2]:
start_date = datetime.datetime(2018,1,1)     #開始日期
end_date= datetime.datetime(2018,12,31)      #結束日期

In [3]:
df_2327 = pdr.DataReader('2327.TW', 'yahoo', start=start_date ,end=end_date)   # 台灣國巨
df_2327.head()

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2018-01-02,295.463989,285.447998,294.628998,295.463989,2750944.0,291.178375
2018-01-03,324.675995,303.809998,308.401001,324.675995,5169187.0,319.966675
2018-01-04,350.549988,328.848999,334.691986,332.605011,12046913.0,327.780670
2018-01-05,346.377014,322.589996,330.101013,337.196014,6620085.0,332.305084
2018-01-08,337.196014,328.432007,337.196014,333.856995,3889273.0,329.014496

In [4]:
df_2327['Date']=df_2327.index             # index 複製到另一欄
df_2327 = df_2327.reset_index(drop=True)  # index變成 0~N
df_2327.head()

,High,Low,Open,Close,Volume,Adj Close,Date
0,295.463989,285.447998,294.628998,295.463989,2750944.0,291.178375,2018-01-02
1,324.675995,303.809998,308.401001,324.675995,5169187.0,319.966675,2018-01-03
2,350.549988,328.848999,334.691986,332.605011,12046913.0,327.780670,2018-01-04
3,346.377014,322.589996,330.101013,337.196014,6620085.0,332.305084,2018-01-05
4,337.196014,328.432007,337.196014,333.856995,3889273.0,329.014496,2018-01-08

In [5]:
##增欄位:fluctuation幅度 tag漲跌平
df_2327['fluctuation']=0
df_2327['tag']='--'
df_2327.head()

,High,Low,Open,Close,Volume,Adj Close,Date,fluctuation,tag
0,295.463989,285.447998,294.628998,295.463989,2750944.0,291.178375,2018-01-02,0,--
1,324.675995,303.809998,308.401001,324.675995,5169187.0,319.966675,2018-01-03,0,--
2,350.549988,328.848999,334.691986,332.605011,12046913.0,327.780670,2018-01-04,0,--
3,346.377014,322.589996,330.101013,337.196014,6620085.0,332.305084,2018-01-05,0,--
4,337.196014,328.432007,337.196014,333.856995,3889273.0,329.014496,2018-01-08,0,--

In [6]:
###計算漲跌
###上漲>3%標示為up 下跌標示為down
for index, row in df_2327.iterrows():
    try:
        margin =(float(df_2327.loc[index,'High']) - float(df_2327.loc[index-1,'Close']) )/ float(df_2327.loc[index-1,'Close'])
        df_2327.loc[index,'fluctuation']=margin
        if margin >0.03:
            df_2327.loc[index,'tag']='up'
        elif margin<-0.03:
            df_2327.loc[index,'tag']='down'
    except:
        continue

In [7]:
###將上漲的資料取出
up_fliter=(df_2327['tag']=='up')
up_2327=df_2327[up_fliter]
up_2327.head()

,High,Low,Open,Close,Volume,Adj Close,Date,fluctuation,tag
1,324.675995,303.809998,308.401001,324.675995,5169187.0,319.966675,2018-01-03,0.098868,up
2,350.549988,328.848999,334.691986,332.605011,12046913.0,327.780670,2018-01-04,0.079692,up
3,346.377014,322.589996,330.101013,337.196014,6620085.0,332.305084,2018-01-05,0.041406,up
7,338.029999,320.502991,330.101013,322.589996,9734149.0,317.910950,2018-01-11,0.067192,up
12,307.148987,295.881012,298.802002,302.140991,8464482.0,297.758545,2018-01-18,0.036622,up

In [8]:
###將下跌的資料取出
down_fliter=(df_2327['tag']=='down')
down_2327=df_2327[down_fliter]
down_2327

,High,Low,Open,Close,Volume,Adj Close,Date,fluctuation,tag
28,281.274994,264.582001,270.424011,276.68399,7312186.0,272.670776,2018-02-09,-0.031609,down
124,1010.000000,959.000000,980.000000,965.00000,12645857.0,965.000000,2018-07-11,-0.033493,down
188,400.500000,384.500000,384.500000,388.00000,27473826.0,388.000000,2018-10-11,-0.054309,down
194,408.000000,389.000000,405.000000,394.00000,26319320.0,394.000000,2018-10-19,-0.032028,down
198,330.500000,315.500000,328.000000,315.50000,24997923.0,315.500000,2018-10-25,-0.053009,down
210,313.500000,304.000000,307.000000,310.00000,21406188.0,310.000000,2018-11-12,-0.047112,down
230,345.000000,322.000000,344.500000,323.50000,23304104.0,323.500000,2018-12-10,-0.032258,down

In [9]:
###將日期做規格處理
upDate=up_2327["Date"].astype(str)
downDate=down_2327["Date"].astype(str)
downDate

28     2018-02-09
124    2018-07-11
188    2018-10-11
194    2018-10-19
198    2018-10-25
210    2018-11-12
230    2018-12-10
Name: Date, dtype: object

In [10]:
###將日期做規格處理
for key,value in downDate.items():
    downDate[key]=datetime.datetime.strptime(value,"%Y-%m-%d")
    print(downDate[key])

2018-02-09 00:00:00
2018-07-11 00:00:00
2018-10-11 00:00:00
2018-10-19 00:00:00
2018-10-25 00:00:00
2018-11-12 00:00:00
2018-12-10 00:00:00

In [11]:
###將日期做規格處理
for key,value in upDate.items():
    upDate[key]=datetime.datetime.strptime(value,"%Y-%m-%d")
    print(upDate[key])

2018-01-03 00:00:00
2018-01-04 00:00:00
2018-01-05 00:00:00
2018-01-11 00:00:00
2018-01-18 00:00:00
2018-01-19 00:00:00
2018-01-22 00:00:00
2018-01-31 00:00:00
2018-02-02 00:00:00
2018-02-07 00:00:00
2018-02-12 00:00:00
2018-02-21 00:00:00
2018-02-23 00:00:00
2018-03-01 00:00:00
2018-03-02 00:00:00
2018-03-05 00:00:00
2018-03-07 00:00:00
2018-03-09 00:00:00
2018-03-12 00:00:00
2018-03-19 00:00:00
2018-03-20 00:00:00
2018-03-21 00:00:00
2018-03-22 00:00:00
2018-03-27 00:00:00
2018-03-29 00:00:00
2018-03-30 00:00:00
2018-04-02 00:00:00
2018-04-09 00:00:00
2018-04-10 00:00:00
2018-04-11 00:00:00
2018-04-13 00:00:00
2018-04-16 00:00:00
2018-04-17 00:00:00
2018-04-18 00:00:00
2018-04-19 00:00:00
2018-04-23 00:00:00
2018-04-26 00:00:00
2018-04-30 00:00:00
2018-05-02 00:00:00
2018-05-04 00:00:00
2018-05-07 00:00:00
2018-05-08 00:00:00
2018-05-09 00:00:00
2018-05-10 00:00:00
2018-05-11 00:00:00
2018-05-14 00:00:00
2018-05-15 00:00:00
2018-05-18 00:00:00
2018-05-21 00:00:00
2018-05-23 00:00:00
2018-05-24 00:00:00
2018-05-25 00:00:00
2018-05-28 00:00:00
2018-06-01 00:00:00
2018-06-04 00:00:00
2018-06-06 00:00:00
2018-06-07 00:00:00
2018-06-11 00:00:00
2018-06-14 00:00:00
2018-06-15 00:00:00
2018-06-21 00:00:00
2018-06-25 00:00:00
2018-06-26 00:00:00
2018-06-27 00:00:00
2018-06-28 00:00:00
2018-06-29 00:00:00
2018-07-02 00:00:00
2018-07-03 00:00:00
2018-07-04 00:00:00
2018-07-05 00:00:00
2018-07-06 00:00:00
2018-07-09 00:00:00
2018-07-10 00:00:00
2018-07-12 00:00:00
2018-07-18 00:00:00
2018-07-19 00:00:00
2018-07-23 00:00:00
2018-07-24 00:00:00
2018-07-25 00:00:00
2018-08-01 00:00:00
2018-08-03 00:00:00
2018-08-06 00:00:00
2018-08-07 00:00:00
2018-08-14 00:00:00
2018-08-16 00:00:00
2018-08-17 00:00:00
2018-08-20 00:00:00
2018-08-24 00:00:00
2018-08-27 00:00:00
2018-08-29 00:00:00
2018-09-11 00:00:00
2018-09-13 00:00:00
2018-09-14 00:00:00
2018-09-19 00:00:00
2018-09-20 00:00:00
2018-09-21 00:00:00
2018-10-09 00:00:00
2018-10-12 00:00:00
2018-10-15 00:00:00
2018-10-16 00:00:00
2018-10-17 00:00:00
2018-10-26 00:00:00
2018-10-31 00:00:00
2018-11-01 00:00:00
2018-11-02 00:00:00
2018-11-07 00:00:00
2018-11-08 00:00:00
2018-11-16 00:00:00
2018-11-21 00:00:00
2018-11-22 00:00:00
2018-11-27 00:00:00
2018-11-28 00:00:00
2018-11-29 00:00:00
2018-12-03 00:00:00
2018-12-11 00:00:00
2018-12-12 00:00:00
2018-12-21 00:00:00
2018-12-27 00:00:00

In [12]:
###讀取論壇資料
df_forum = pd.read_csv("bda2019_dataset/forum2.csv",encoding="utf-8")
df_forum[['post_time','title','content']]

,post_time,title,content
0,2016/1/1 2:01:00,自刪,不小心發錯版主請幫忙刪除文章謝謝
1,2016/1/1 10:41:00,傳超微已打算將訂單下給格羅方德,台積電爭奪超微下一代繪圖處理器失利，因為傳超微已打算將訂單下給格羅方德（GlobalFoun...
2,2016/1/1 10:45:00,蘋果將另尋成長動能發動購併 ??,有分析師認為 蘋果將另尋成長動能，或許會動用深到不行的口袋，發動購併，可能目標包括 Adob...
3,2016/1/1 11:19:00,[詢問] 停徵證所稅,新聞相關報導:<BR>[立法院院會去年11月三讀修正通過所得稅法部分條文，刪除有關證所稅相關...
4,2016/1/1 12:29:00,網路出金,請問一下，網路出金是什麼？謝謝各位喔。
5,2016/1/1 12:49:00,這情況 是銀行多給利息嗎！,大家，新年快樂<BR>想請問大家，在網銀設定定存半年，在今天105/01/01到期，<BR>...
6,2016/1/1 16:15:00,元大S&P500或開美國卷商買S&P500哪個好?,這陣子知道元大也有S&P500<BR>且自己上網查閱了另一種<BR>就是線上開美國證卷戶的方...
7,2016/1/1 16:28:00,請問各位學技術分析的大大們 那些指標好用呢？,請問各位大大 小弟如果想作短線 有那些技術指標比較實用比較準的呢？可否推薦一下呢？
8,2016/1/1 16:59:00,貧富差距不斷增加，你該如何自保？,台灣曾經有過均富的黃金時代!!<BR>那個時候是台灣經濟起飛的時候<BR>還記得台灣的平均所...
9,2016/1/1 20:00:00,鴻海股價最近低迷,鴻海最近股價低迷 是發生什麼狀況嗎?<BR>是否可在進場?求解
10,2016/1/1 22:21:00,賠，賠，賠 -- 我過的好難受啊！,2015 真難受。<BR>賠了 5%。<BR>有人比我慘嗎？
11,2016/1/1 22:26:00,"南非幣要破2了,要停損嗎?還是繼續加碼.","南非幣從4.2開始買,都存定存,3.4時又大買 一批,<BR>總共約65萬南非幣,我也不知道..."
12,2016/1/1 22:43:00,大成感覺不錯 有人上車了嗎???,理由<BR>1 成交量創新高<BR>2 股價創8/7以來新高<BR>3 近期法人持續買超<B...
13,2016/1/2 1:55:00,2016看好的概念股,過去的已經過去，總該有些成長，把跌倒當經驗，展望未來有甚麼是未來十年的希望?<BR>這些概念...
14,2016/1/2 9:31:00,想請問使用現金加油的加油卡(非信用卡),因為各大加油站網站上都沒寫~~~<BR>不知道有大大有推薦哪幾家有可申辦使用現金加油的優惠加...
15,2016/1/2 10:03:00,請問金管會接管朝陽人壽.儲蓄險保戶會有哪些影響?,金管會接管朝陽人壽 <BR>請問短年期儲蓄險保戶會有哪些影響?<BR>===========...
16,2016/1/2 11:04:00,信用卡建議~~,小弟每月固定會刷高鐵回數票(8000)<BR>另外手機跟電視帳單有中華電信、亞太電信、TBC...
17,2016/1/2 12:23:00,人民幣又見急跌 2015全年跌幅註定寫新紀錄,人民幣兌美元周四 (31日) 持續下跌，在歷經近 5 個月大幅波動之後，全年跌幅預計達 4....
18,2016/1/2 16:14:00,【請教】選股軟體 (泰穎製作所),"請問各位高手<BR>大家在選股時,會另外再使用特別的軟體來選股嗎?<BR>這套軟體有沒有人使..."
19,2016/1/2 17:06:00,請問機車險，50cc的要怎樣選擇？,只要保強制和第三責任嗎？<BR>保那家較好，<BR>有推薦的保險公司？<BR>怎樣搭配好<B...
20,2016/1/2 17:11:00,加薪能救景氣 ?,加薪能救景氣 ?<BR>那為什麼現在可以加不趕快加呢 ? 為什麼現在不把基本工資調到4萬 ?
21,2016/1/2 19:04:00,９月那波急拉上去，看到一線生機！成功獲利,相信大家，對於８╱２５還記憶猶新吧！！<BR>當大家都悲觀的時候，從７２００點，一口氣漲到８...
22,2016/1/2 20:58:00,該怎麼創造被動收入 達每個月有三萬,小弟我現在存款有82萬多<BR>每個月基本薪資有6萬5 偶爾會有客製化家具兼差 (但這個兼差...
23,2016/1/2 23:39:00,100 萬現金支出怎麼得到優惠?,小弟因為要買車，故將有大筆現金支出，約100萬.<BR>想問看看有沒有其他方式讓花出去的錢收...
24,2016/1/3 0:30:00,2016/1/1 至 2/29,接替2015年持股<BR>觀察2015年的勝敗數<BR>10天的周期<BR>勝率最高<BR>...
25,2016/1/3 13:13:00,國泰金尾盤,在這天 國泰金尾盤買單大灌快1萬張<BR> 此時的我只想等明天開盤空國泰金... <BR>大...
26,2016/1/3 15:14:00,請問現行的新股抽籤制度 ???,http://udn.com/news/story/7239/1218822-IPO%E7%...
27,2016/1/3 15:37:00,怒火特攻隊真是大爛片,"最後一場戰鬥戲碼真的是沒服過兵役的人編導的.<BR>美軍既已反攻至德國領土, 表示勝利在望,..."
28,2016/1/3 15:44:00,請教機車險幾個問題,請問下<BR>1.<BR>若機車是成年人的<BR>若將來有保第三和強制險<BR>無照未成年小...
29,2016/1/3 16:10:00,理財賺錢有時是天命,同學A買了100張股票，股價大漲加上股利豐富，幾年後身價破數千萬<BR>同學B買了前公司股票...
...,...,...,...
25922,2018/12/30 7:09:00,ASUS華碩 歷史股價觀察買低賣高的高手券商,ASUS華碩是一間台灣之光的上市公司，一般來說國人多少都有用過他的電子產品，像是桌機、筆電、...
25923,2018/12/30 9:16:00,債券,因市場諸多不可測因素<BR>為避免網友真實仿效而導致虧損<BR>因此版主選擇將此版下架<BR...
25924,2018/12/30 10:01:00,基本工資又漲了，你拿到了嗎？,1/1開始<BR>基本工資又漲了<BR>小姐早早就問我<BR>她的工資怎麼算<BR>工作了一...
25925,2018/12/30 10:11:00,我的基金投資配置,年底前因為急需用到一筆錢，只能先把手上的基金先贖回，20多萬的本金，小虧幾千元。<BR>原先...
25926,2018/12/30 10:50:00,10年來最慘!信用卡好康大縮水,搶在跨入2019年前夕，信用卡新年度權益全數出爐，不只回饋率腰斬，能想到的各項權益，包括市區...
25927,2018/12/30 11:49:00,美金高利定存?,想請問那家最高?<BR>年利率 單純定存不做商品<BR>不要階梯式跟短期那種<BR>謝謝
25928,2018/12/30 13:15:00,利安資金越南基金 VS 越南ETF(VNM) @五線譜投資術,最近看到五線譜投資術作者在FB上有簡短提到越南市場的現況與前景，<BR>專業又忙碌如他還是花...
25929,2018/12/30 16:34:00,請問股票股利約幾月公佈,請問股票股票股利約在幾月會公佈？
25930,2018/12/30 18:26:00,請問大家看年報季報是用什麼平台看的?,"因為現在很少公司會發紙本了,都用PDF檔,如果在電腦上看實在很傷眼,而且一家要看十年以上,就..."
25931,2018/12/30 21:35:00,台灣現有ETF(107/12/28)。,1.黃底 ─ 50億以上，0.4%以下。<BR>2.藍底 ─ 5億以下，1%以上。<BR>3...
25932,2018/12/30 22:55:00,2019元旦行情，台股恐上看11000,1/2漲500點<BR>1/3漲400點<BR>1/4漲300點<BR>不要說不可能，<BR...
25933,2018/12/31 1:16:00,買iShares US Preferred Stock ETF (PFF)做為長期投資，比起...,原本想說買iShares US Preferred Stock ETF (PFF)會比買個別...
25934,2018/12/31 2:32:00,有個貸款問題想請教,小弟有一筆國泰世華信貸分84期年利率9%多(貸這筆時因當時評分條件較差，近一年有預借現金及信...
25935,2018/12/31 7:22:00,2019可取代line pay的信用卡？,2%且無回饋金額限制<BR>和linepay 定位一樣的卡有嗎？<BR>用慣linepay ...
25936,2018/12/31 9:43:00,0050是不是請了很多寫手，坊間一大票文章都是推崇,首先不可否認0050在這幾年確實是賺了股利贏了價差，許多文章也極力推崇，元大就賺管理費經理費...
25937,2018/12/31 11:17:00,信用卡分期 & 小額信貸,如果有一筆約30萬的需求，請問是刷卡後申請信用卡分期(最多30期)好? 還是申請小額信貸(最...
25938,2018/12/31 11:49:00,防洗錢需要這麼擾民 ? 資料更新變擾民運動,防洗錢新制 資料更新變擾民運動<BR><BR> <BR>2018-12-31 01:53聯合...
25939,2018/12/31 13:21:00,股市的the less is more,在股票的世界裡，我是一位信奉「the less is more」的投資人，換句話說，我相信做...
25940,2018/12/31 14:54:00,想掛機賺錢看這邊 掛機只要掛到1BTC就等於賺3949.3美金,想掛機賺錢看這邊 掛機只要掛到1BTC就等於賺3949.3美金<BR>想挑戰看看嗎? 掛機賺...
25941,2018/12/31 15:06:00,電腦放著在那邊也是閒著�� 不如拿來簡單又免費挖比特幣吧~~,超低提款門檻只要(0.0004000 BTC)就可以提領！<BR>以運算速度26左右大概4?...
25942,2018/12/31 16:21:00,2430燦坤當定存股可否,配股配息都5%以上<BR>股價來到相對低點<BR>有人有關注到嗎
25943,2018/12/31 16:22:00,不小心公開 證卷帳號11碼 怎辦,不小心公開 證卷帳號11碼 怎辦？<BR>會被盜用嗎？
25944,2018/12/31 17:49:00,防洗錢新制…銀行資料更新 變擾民運動,新聞資料<BR>請問<BR>我不知道我是否有被通知，<BR>我錢那麼少，<BR>到底要不要K...
25945,2018/12/31 18:21:00,2019台新gogo卡超商問題,台新gogo說<BR>2019年回饋之3.5%<BR>排除一切任何一切型式的超商消費<BR>...
25946,2018/12/31 18:37:00,改變消費習慣，你也可以翻轉人生,行動支付正在改變我們的消費模式，食衣住行現在越來越方便，只要手機「嗶」一下就通通搞定，而支付...
25947,2018/12/31 18:59:00,每年保費約250萬，辦哪一張信用卡繳費最好,請問這裡有信用卡達人可以指教一下嗎?每年的保費.都是儲蓄險多，大約250-300萬之間，<B...
25948,2018/12/31 20:09:00,一則美債新聞分享,"這是今天的新聞,作為一位投資者,看完後也分享給大家,但我沒投資美債,對新聞內容也沒有評論~<..."
25949,2018/12/31 20:16:00,股市贏家魔法書-股海真經 全文免費線上閱覽,股市贏家魔法書-股海真經<BR>全文免費線上閱覽<BR>http://stock.nett.tw
25950,2018/12/31 20:27:00,2018年中國夢(雞金暴跌),2018年最后一?交易日落下帷幕，?受?注的公募基金年度排名大??埃落定。<BR>在288只...
25951,2018/12/31 21:20:00,股票為什麼會漲？股票為什麼會跌？,股票為什麼會漲？股票為什麼會跌？<BR>股票為什麼會漲？股票為什麼會跌？ - Google ...

In [13]:
###開始做兩種資料表中的時間比對
##資料時間規格處理
forumDate=df_forum['post_time'].astype(str)
for i in range(len(forumDate)):
    try:
        forumDate[i]=datetime.datetime.strptime(forumDate[i],"%Y-%m-%d %H:%M:%S").replace(hour=0, minute=0,second=0)
    except ValueError:
        forumDate[i]=datetime.datetime.strptime(forumDate[i],"%Y/%m/%d %H:%M:%S").replace(hour=0, minute=0,second=0)
forumDate.head()

0    2016-01-01 00:00:00
1    2016-01-01 00:00:00
2    2016-01-01 00:00:00
3    2016-01-01 00:00:00
4    2016-01-01 00:00:00
Name: post_time, dtype: object

In [14]:
###文章處理
cutlist = "「」<>/:：;；,、，。？＂’，.。！？?,.｢\"\'\\\n\r《》“”!@#$%^&*()0123456789（）abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
down_title_list=[]
down_content_list=[]
up_title_list=[]
up_content_list=[]

In [15]:
###符號處裡 (未完全
def deDot(line):
        sentence = ""
        for word in line:
            if word not in cutlist: #如果文字不是標點符號，就把字加到句子中
                sentence += word
        return(sentence)

In [16]:
###比對時間，若一樣則將標題和內容存進list
for key,value in downDate.items():
    for i in range(len(forumDate)):
        if(not (downDate[key].strftime("%Y")==forumDate[i].strftime("%Y"))):
            continue
        if(not (downDate[key].strftime("%m")==forumDate[i].strftime("%m"))):
            continue
        if(downDate[key].strftime("%d")==forumDate[i].strftime("%d")):
            down_title_list.append(deDot(df_forum.loc[i,'title']))
            down_content_list.append(deDot(df_forum.loc[i,'content']))

In [17]:
for key,value in upDate.items():
    for i in range(len(forumDate)):
        if(not (upDate[key].strftime("%Y")==forumDate[i].strftime("%Y"))):
            continue
        if(not (upDate[key].strftime("%m")==forumDate[i].strftime("%m"))):
            continue
        if(upDate[key].strftime("%d")==forumDate[i].strftime("%d")):
            up_title_list.append(deDot(df_forum.loc[i,'title']))
            up_content_list.append(deDot(df_forum.loc[i,'content']))

In [19]:
print(up_title_list[:5])

['一張表秒懂年元旦金融新措施', '關於 ', '橘子  今天漲停', '人民幣優利定存', '美國運通是不是快倒了-卡主蓋大樓']